POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6Im5pY2tAZ21haWwuY29tIiwiaWF0IjoxNzI5OTI1Nzc1LCJleHAiOjE3Mjk5MjkzNzUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.X6BggNOn-nhTbjAhBYlnXRyDu6cJSU7rbxdaLVPyHV8

{
  "title": "test post 2",
  "postType": "post",
  "slug": "test-post-8",
  "status": "draft",
  "content": "This is a test post body",
  "schema": "{\"type\": \"test\"}",
  "publishedOn": "2024-09-22T14:00:00.000Z",
  "tags": [1, 2],
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\":true, \"footerActive\":true}"
  }

}