POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Mark",
  "lastName": "Doe",
  "email": "mark_doe@gmail.com",
  "password": "password1234!"
}

POST http://localhost:3000/users/create-many
Content-Type: application/json

{
  "users": [
    {
      "firstName": "Miranda",
      "lastName": "Doe",
      "email": "miranda@gmail.com",
      "password": "password1234!"
    },
    {
      "firstName": "Lisa",
      "lastName": "Doe",
      "email": "lisa@gmail.com",
      "password": "password1234!"
    }
  ]
}